const friends=[['Moana','moana'],['Thelma','thelma'],['Cats & Peachtopia','cats'],['Ms. Rachel','ms-rachel'],['Dragon','dragon'],['Shrek','shrek'],['Zootopia','zootopia'],['Sing','sing'],['Home','home'],['Secret Life of Pets','pets'],['UglyDolls','uglydolls'],['K-Pop Demon Hunters','kpop'],['Blippi','blippi'],['Batman','batman'],['Leo','leo'],['Back to the Outback','outback'],['Coco','coco']];
const levels=[['🌱','Little',3],['🌻','Growing',6],['⭐','Super',8],['🌟','All Stars',17]];
let level=0,cards=[],up=[],matched=0,moves=0,locked=false,sound=true,timer;
const $=id=>document.getElementById(id); const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function tone(win=false){if(!sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=new A;[win?523:330,win?659:392,...(win?[784]:[])].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.001,c.currentTime+i*.08);g.gain.exponentialRampToValueAtTime(.1,c.currentTime+i*.08+.01);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+i*.08+.16);o.connect(g).connect(c.destination);o.start(c.currentTime+i*.08);o.stop(c.currentTime+i*.08+.18)})}
function renderLevels(){$('levels').innerHTML=levels.map((l,i)=>`<button class="${i===level?'on':''}" data-level="${i}"><b>${l[0]}</b>${l[1]}<small>${l[2]} pairs</small></button>`).join('');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=+b.dataset.level;renderLevels();start()})}
function start(){clearTimeout(timer);locked=false;up=[];matched=0;moves=0;$('win').hidden=true;const picked=shuffle(friends).slice(0,levels[level][2]);cards=shuffle(picked.flatMap((f,i)=>[{...f,id:i+'a',done:false},{...f,id:i+'b',done:false}]));render()}
function render(){$('score').textContent=`${matched} of ${levels[level][2]} pairs`;$('progress').style.width=`${matched/levels[level][2]*100}%`;$('grid').className=`grid size-${levels[level][2]}`;$('grid').innerHTML=cards.map((c,i)=>`<button class="card ${(up.includes(i)||c.done)?'up':''} ${c.done?'done':''}" data-i="${i}" aria-label="${up.includes(i)||c.done?c[0]:'Hidden card '+(i+1)}"><span class="inner"><span class="back">?<i>✦</i></span><span class="front"><img src="characters/${c[1]}.webp" alt="${c[0]}"><strong>${c[0]}</strong>${c.done?'<i class="check">✓</i>':''}</span></span></button>`).join('');document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>flip(+b.dataset.i))}
function flip(i){if(locked||cards[i].done||up.includes(i))return;tone();up.push(i);render();if(up.length<2)return;locked=true;moves++;const[a,b]=up;if(cards[a][0]===cards[b][0])timer=setTimeout(()=>{cards[a].done=cards[b].done=true;matched++;up=[];locked=false;tone(true);render();if(matched===levels[level][2]){setTimeout(()=>{$('turns').textContent=`${matched} happy pairs in ${moves} turns.`;$('win').hidden=false},300)}},400);else timer=setTimeout(()=>{up=[];locked=false;render()},900)}
$('mix').onclick=start;$('again').onclick=start;$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'🔊':'🔇';$('sound').ariaLabel=sound?'Turn sound off':'Turn sound on'};renderLevels();start();
