import "./memory-game.css";

const friends = [["Moana","moana"],["Thelma","thelma"],["Cats & Peachtopia","cats"],["Ms. Rachel","ms-rachel"],["Dragon","dragon"],["Shrek","shrek"],["Zootopia","zootopia"],["Sing","sing"],["Home","home"],["Secret Life of Pets","pets"],["UglyDolls","uglydolls"],["K-Pop Demon Hunters","kpop"],["Blippi","blippi"],["Batman","batman"],["Leo","leo"],["Back to the Outback","outback"],["Coco","coco"]];
const levels = [["🌱","Little",3],["🌻","Growing",6],["⭐","Super",8],["🌟","All Stars",17]];
const shuffle = (items) => { const copy = [...items]; for (let i = copy.length - 1; i; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; };

export function mountMemoryGame(root) {
  root.className = "memory-game";
  root.innerHTML = `<main class="shell"><header><div class="brand"><b>✿</b><span>Esme's<small>Memory Garden</small></span></div><button data-sound aria-label="Turn sound off">🔊</button></header><section class="intro"><p>✦ FIND THE MATCHING FRIENDS! ✦</p><h1>Flip, find &amp; <em>smile!</em></h1><div data-levels class="levels"></div></section><section class="game"><div class="status"><strong data-score>0 of 3 pairs</strong><div class="track"><i data-progress></i></div><button data-mix>↻ Mix!</button></div><div data-grid class="grid"></div><p class="hint">☝️ Tap a card to peek!</p></section></main><div data-win class="win" hidden><div class="win-card"><div>🏆</div><p>HOORAY! YOU FOUND THEM ALL!</p><h2>You're a memory <em>star!</em></h2><span data-turns></span><button data-again>Play again ✨</button></div></div>`;
  const $ = (selector) => root.querySelector(selector);
  let level = 0, cards = [], up = [], matched = 0, moves = 0, locked = false, sound = true, timer;
  function tone(win = false) { if (!sound) return; const Audio = window.AudioContext || window.webkitAudioContext; if (!Audio) return; const context = new Audio(); [win ? 523 : 330, win ? 659 : 392, ...(win ? [784] : [])].forEach((frequency, index) => { const oscillator = context.createOscillator(), gain = context.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(.001, context.currentTime + index * .08); gain.gain.exponentialRampToValueAtTime(.1, context.currentTime + index * .08 + .01); gain.gain.exponentialRampToValueAtTime(.001, context.currentTime + index * .08 + .16); oscillator.connect(gain).connect(context.destination); oscillator.start(context.currentTime + index * .08); oscillator.stop(context.currentTime + index * .08 + .18); }); }
  function renderLevels() { $("[data-levels]").innerHTML = levels.map((item, index) => `<button class="${index === level ? "on" : ""}" data-level="${index}"><b>${item[0]}</b>${item[1]}<small>${item[2]} pairs</small></button>`).join(""); root.querySelectorAll("[data-level]").forEach((button) => { button.onclick = () => { level = +button.dataset.level; renderLevels(); start(); }; }); }
  function render() { $("[data-score]").textContent = `${matched} of ${levels[level][2]} pairs`; $("[data-progress]").style.width = `${matched / levels[level][2] * 100}%`; const grid = $("[data-grid]"); grid.className = `grid size-${levels[level][2]}`; grid.innerHTML = cards.map((card, index) => `<button class="card ${(up.includes(index) || card.done) ? "up" : ""} ${card.done ? "done" : ""}" data-card="${index}" aria-label="${up.includes(index) || card.done ? card[0] : `Hidden card ${index + 1}`}"><span class="inner"><span class="back">?<i>✦</i></span><span class="front"><img src="/games/memory-game/characters/${card[1]}.webp" alt="${card[0]}"><strong>${card[0]}</strong>${card.done ? '<i class="check">✓</i>' : ""}</span></span></button>`).join(""); root.querySelectorAll("[data-card]").forEach((button) => { button.onclick = () => flip(+button.dataset.card); }); }
  function start() { clearTimeout(timer); locked = false; up = []; matched = 0; moves = 0; $("[data-win]").hidden = true; const picked = shuffle(friends).slice(0, levels[level][2]); cards = shuffle(picked.flatMap((friend, index) => [[...friend, `${index}a`, false], [...friend, `${index}b`, false]])); render(); }
  function flip(index) { if (locked || cards[index].done || up.includes(index)) return; tone(); up.push(index); render(); if (up.length < 2) return; locked = true; moves++; const [first, second] = up; if (cards[first][0] === cards[second][0]) timer = setTimeout(() => { cards[first].done = cards[second].done = true; matched++; up = []; locked = false; tone(true); render(); if (matched === levels[level][2]) setTimeout(() => { $("[data-turns]").textContent = `${matched} happy pairs in ${moves} turns.`; $("[data-win]").hidden = false; }, 300); }, 400); else timer = setTimeout(() => { up = []; locked = false; render(); }, 900); }
  $("[data-mix]").onclick = start; $("[data-again]").onclick = start; $("[data-sound]").onclick = () => { sound = !sound; $("[data-sound]").textContent = sound ? "🔊" : "🔇"; $("[data-sound]").ariaLabel = sound ? "Turn sound off" : "Turn sound on"; }; renderLevels(); start();
  return () => clearTimeout(timer);
}
